/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataTypeCard: typeof import('./src/components/datatype/DataTypeCard.vue')['default']
    DataTypeList: typeof import('./src/components/datatype/DataTypeList.vue')['default']
    DataTypeSelect: typeof import('./src/components/DataTypeSelect.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExecuteConfig: typeof import('./src/components/form/ExecuteConfig.vue')['default']
    ExecuteConfigModal: typeof import('./src/components/modal/ExecuteConfigModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./src/components/card/TaskCard.vue')['default']
    TaskGroupCard: typeof import('./src/components/card/TaskGroupCard.vue')['default']
    TaskGroupModal: typeof import('./src/components/modal/TaskGroupModal.vue')['default']
    UserCookieModal: typeof import('./src/components/modal/UserCookieModal.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const DataTypeCard: (typeof import('./src/components/datatype/DataTypeCard.vue'))['default']
  const DataTypeList: (typeof import('./src/components/datatype/DataTypeList.vue'))['default']
  const DataTypeSelect: (typeof import('./src/components/DataTypeSelect.vue'))['default']
  const ElButton: (typeof import('element-plus/es'))['ElButton']
  const ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox']
  const ElCheckboxGroup: (typeof import('element-plus/es'))['ElCheckboxGroup']
  const ElCol: (typeof import('element-plus/es'))['ElCol']
  const ElDialog: (typeof import('element-plus/es'))['ElDialog']
  const ElDivider: (typeof import('element-plus/es'))['ElDivider']
  const ElEmpty: (typeof import('element-plus/es'))['ElEmpty']
  const ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
  const ElIcon: (typeof import('element-plus/es'))['ElIcon']
  const ElInput: (typeof import('element-plus/es'))['ElInput']
  const ElProgress: (typeof import('element-plus/es'))['ElProgress']
  const ElRadio: (typeof import('element-plus/es'))['ElRadio']
  const ElRadioButton: (typeof import('element-plus/es'))['ElRadioButton']
  const ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
  const ElSwitch: (typeof import('element-plus/es'))['ElSwitch']
  const ElText: (typeof import('element-plus/es'))['ElText']
  const ElTooltip: (typeof import('element-plus/es'))['ElTooltip']
  const ExecuteConfig: (typeof import('./src/components/form/ExecuteConfig.vue'))['default']
  const ExecuteConfigModal: (typeof import('./src/components/modal/ExecuteConfigModal.vue'))['default']
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
  const TaskCard: (typeof import('./src/components/card/TaskCard.vue'))['default']
  const TaskGroupCard: (typeof import('./src/components/card/TaskGroupCard.vue'))['default']
  const TaskGroupModal: (typeof import('./src/components/modal/TaskGroupModal.vue'))['default']
  const UserCookieModal: (typeof import('./src/components/modal/UserCookieModal.vue'))['default']
}
