/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddSectionModal: typeof import('./components/AddSectionModal.vue')['default']
    ArchiveSelectDialog: typeof import('./components/ArchiveSelectDialog/ArchiveSelectDialog.vue')['default']
    DraggableList: typeof import('./components/DraggableList/DraggableList.vue')['default']
    EditSeasonModal: typeof import('./components/EditSeasonModal.vue')['default']
    EditSectionModal: typeof import('./components/EditSectionModal.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EpisodeList: typeof import('./components/EpisodeList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveDataModal: typeof import('./components/SaveDataModal.vue')['default']
    SeasonItem: typeof import('./components/SeasonItem.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const AddSectionModal: typeof import('./components/AddSectionModal.vue')['default']
  const ArchiveSelectDialog: typeof import('./components/ArchiveSelectDialog/ArchiveSelectDialog.vue')['default']
  const DraggableList: typeof import('./components/DraggableList/DraggableList.vue')['default']
  const EditSeasonModal: typeof import('./components/EditSeasonModal.vue')['default']
  const EditSectionModal: typeof import('./components/EditSectionModal.vue')['default']
  const ElAlert: typeof import('element-plus/es')['ElAlert']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const EpisodeList: typeof import('./components/EpisodeList.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SaveDataModal: typeof import('./components/SaveDataModal.vue')['default']
  const SeasonItem: typeof import('./components/SeasonItem.vue')['default']
}