/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BiliComment: typeof import('./components/BiliComment.vue')['default']
    BiliCommentsSection: typeof import('./components/BiliCommentsSection.vue')['default']
    BiliReply: typeof import('./components/BiliReply.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const BiliComment: typeof import('./components/BiliComment.vue')['default']
  const BiliCommentsSection: typeof import('./components/BiliCommentsSection.vue')['default']
  const BiliReply: typeof import('./components/BiliReply.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}